---
title: "Kaggle Store Sales"
output: html_notebook
---


# Short Solution

```{r}
# url_short_solution <- "https://www.kaggle.com/code/coolman145/simple-baseline-r-forecasting-with-fable-0-42401"
# 
# # Import Data =================================================================
# suppressMessages(library(tidyverse))
# suppressMessages(library(tsibble))
# suppressMessages(library(fable))
# 
# train = read_csv('./data/train.csv')
# test = read_csv('./data/test.csv')
# 
# # train model =================================================================
# pred <- train %>%
#   tsibble(index = date, key = c(store_nbr, family)) %>%
#   fill_gaps(sales = 0) %>%
#   model(ets = ETS(sqrt(sales))) %>%
#   forecast(h = "16 days")
# 
# write_csv(pred, file = "pred.csv")
# 
# ## Export Test Data Results ===================================================
# results <- test %>%
#   left_join(pred, by = c("store_nbr", "family", "date")) %>%
#   select(id, .mean)
# 
# colnames(results) <- c("id","sales")
# 
# write_csv(results, file = "submission.csv")
```

# Load Packages and Data
```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tsibble))
suppressPackageStartupMessages(library(fable))
suppressPackageStartupMessages(library(fpp3))

train <- readr::read_csv('./data/train.csv', 
                 col_types = cols(.default = "d", 
                                  date = "D", 
                                  family = "c"))

test <- readr::read_csv('./data/test.csv', 
                 col_types = cols(.default = "d", 
                                  date = "D", 
                                  family = "c"))
```

# EDA
```{r}
str(train)
```
Convert to tsibble:
```{r}
train <- tsibble(train, 
                 index = date, 
                 key = c(store_nbr, family))
str(train, max.level = 2)
```

```{r}
# review zero sales; do we need these rows?; we clean it up later with fill_gaps()
dplyr::arrange(train[train$sales == 0,], store_nbr)
```


```{r}
summary(train)
```

```{r}
table(train$family)
```
```{r}
head(train)
```

## Plot
### Aggregate Sales and Plot TS
```{r}
train |>
  # group_by(family) |>
  index_by(date) |>
  summarise(sales = sum(sales))
```

```{r}
train |>
  summarise(sales = sum(sales)) |>
  autoplot(.vars = sales) +
  labs(title = "Sales",
       subtitle = "Consolidated",
       x = "Date",
       y = "Sales")
```

### Decomposition Table STL
```{r}
train_consolidated <- 
  train |>
  summarise(sales = sum(sales)) |>
  fill_gaps(sales = 0)

# fill_gaps: 2013-12-25 did not exist in the original 'train' dataset, but was created with zero values by the fill_gaps function
train[train$date == "2013-12-25",]
train_consolidated[train_consolidated$sales == 0,]

# create STL decomposition model
dcmp <- train_consolidated |>
  fabletools::model(stl = STL(sales))

fabletools::components(dcmp)
```

Plot decomposition model:
```{r}
fabletools::components(dcmp) |>
  autoplot()
```

# Train Model


# Prediction


# Create Submission File